# Default values
ROCM_VERSION ?= 7.1
UBUNTU_VERSION ?= 24.04
PYTORCH_VERSION ?= 2.8.0
PYTHON_VERSION ?= 3.12
COMFYUI_VERSION ?= v0.3.71
COMFYUI_MANAGER_VERSION ?= 3.37.1
COMFY_CLI_VERSION ?= 1.5.3
IMAGE_VERSION ?= 0.0.1

BASE_IMAGE_VERSION ?= rocm$(ROCM_VERSION)_ubuntu$(UBUNTU_VERSION)_py$(PYTHON_VERSION)_pytorch_release_$(PYTORCH_VERSION)

# Derived tags
TAG_COMFYUI := comfyui$(COMFYUI_VERSION)
TAG_ROCM := rocm$(ROCM_VERSION)
IMAGE_NAME := blivioniag/comfyui_rocm_pytorch

build:
	podman build \
		--build-arg IMAGE_VERSION=$(IMAGE_VERSION) \
		--build-arg BASE_IMAGE_VERSION=$(BASE_IMAGE_VERSION) \
		--build-arg COMFYUI_VERSION=$(COMFYUI_VERSION) \
		--build-arg COMFYUI_MANAGER_VERSION=$(COMFYUI_MANAGER_VERSION) \
		--build-arg COMFY_CLI_VERSION=$(COMFY_CLI_VERSION) \
		-t $(IMAGE_NAME):latest \
		-t $(IMAGE_NAME):$(IMAGE_VERSION) \
		-t $(IMAGE_NAME):$(IMAGE_VERSION)-$(TAG_COMFYUI) \
		-t $(IMAGE_NAME):$(IMAGE_VERSION)-$(TAG_ROCM) \
		-t $(IMAGE_NAME):$(IMAGE_VERSION)-$(TAG_COMFYUI)-$(TAG_ROCM) \
		-t $(IMAGE_NAME):$(TAG_COMFYUI) \
		-t $(IMAGE_NAME):$(TAG_COMFYUI)-$(TAG_ROCM) \
		-t $(IMAGE_NAME):$(TAG_ROCM) \
		.